language: node_js
node_js:
  - 6
  - 8
  - 10
script:
  - npm run build
  - npm run test
notifications:
  email:
    on_success: change
    on_failure: change
sudo: false
after_success:
  - npm install -g codecov
  - codecov

